# Form implementation generated from reading ui file 'zadanie1.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_guishka(object):
    def setupUi(self, guishka):
        guishka.setObjectName("guishka")
        guishka.resize(828, 801)
        self.pushButton = QtWidgets.QPushButton(parent=guishka)
        self.pushButton.setGeometry(QtCore.QRect(310, 510, 171, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(parent=guishka)
        self.textBrowser.setGeometry(QtCore.QRect(20, 190, 261, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=guishka)
        self.textBrowser_2.setGeometry(QtCore.QRect(280, 190, 261, 51))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=guishka)
        self.textBrowser_3.setGeometry(QtCore.QRect(540, 190, 261, 51))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.listView_2 = QtWidgets.QListView(parent=guishka)
        self.listView_2.setGeometry(QtCore.QRect(280, 240, 256, 192))
        self.listView_2.setObjectName("listView_2")
        self.listView_3 = QtWidgets.QListView(parent=guishka)
        self.listView_3.setGeometry(QtCore.QRect(540, 240, 256, 192))
        self.listView_3.setMaximumSize(QtCore.QSize(256, 16777215))
        self.listView_3.setObjectName("listView_3")
        self.listView = QtWidgets.QListView(parent=guishka)
        self.listView.setGeometry(QtCore.QRect(20, 240, 256, 192))
        self.listView.setObjectName("listView")
        self.checkBox = QtWidgets.QCheckBox(parent=guishka)
        self.checkBox.setGeometry(QtCore.QRect(320, 80, 191, 21))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=guishka)
        self.checkBox_2.setGeometry(QtCore.QRect(320, 140, 251, 20))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=guishka)
        self.checkBox_3.setGeometry(QtCore.QRect(320, 120, 221, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=guishka)
        self.checkBox_4.setGeometry(QtCore.QRect(320, 100, 231, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=guishka)
        self.textBrowser_4.setGeometry(QtCore.QRect(180, 10, 471, 51))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton_2 = QtWidgets.QPushButton(parent=guishka)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 470, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=guishka)
        self.pushButton_3.setGeometry(QtCore.QRect(340, 470, 171, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=guishka)
        self.pushButton_4.setGeometry(QtCore.QRect(510, 470, 171, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(parent=guishka)
        self.textBrowser_5.setGeometry(QtCore.QRect(90, 560, 291, 51))
        self.textBrowser_5.setObjectName("textBrowser_5")

        self.retranslateUi(guishka)
        QtCore.QMetaObject.connectSlotsByName(guishka)

    def retranslateUi(self, guishka):
        _translate = QtCore.QCoreApplication.translate
        guishka.setWindowTitle(_translate("guishka", "Dialog"))
        self.pushButton.setText(_translate("guishka", "Закрыть приложение"))
        self.textBrowser.setHtml(_translate("guishka", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Груз</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("guishka", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Вагон</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24pt;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("guishka", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Габариты</span></p></body></html>"))
        self.checkBox.setText(_translate("guishka", "Лёгкий(3 вагона,0 ошибок)"))
        self.checkBox_2.setText(_translate("guishka", "Богоподобный(20 вагонов,0 ошибок)"))
        self.checkBox_3.setText(_translate("guishka", "Трудный(10 вагонов ,1 ошибка)"))
        self.checkBox_4.setText(_translate("guishka", "Нормальный(5 вагонов,0 ошибок)"))
        self.textBrowser_4.setHtml(_translate("guishka", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Уровень сложность</span></p></body></html>"))
        self.pushButton_2.setText(_translate("guishka", "Сброс выбора"))
        self.pushButton_3.setText(_translate("guishka", "Проверить"))
        self.pushButton_4.setText(_translate("guishka", "Сохранить результат"))
        self.textBrowser_5.setHtml(_translate("guishka", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Результат</span></p></body></html>"))
